### ISSUE TITLE
TypeError: Cannot read property 'split' of null

### ISSUE THREAD

**Issue by helllicht** [sylvainjule/kirby-markdown-field#81] opened 2019-08-16 11:40 UTC
Since updating Kirby to 3.2.x (3.2.3 in our case) the panel is showing the following error when switching pages (e.g. with right/left arrows) from pages that use the markdown field.

Here's the error: `Cannot read property 'split' of null`
It also shows up as a warning in the console.

We're not quite sure if it's really an issue with the plugin or rather [something that changed in the panel ](https://github.com/getkirby/kirby/issues/2007)that now causes the error in combination with the plugin.

**Comment by LeBenLeBen** [comment] 2019-08-22 12:40
I confirm I have this issue as well with Kirby 3.2.3. The issue comes from this specific line:

```js
return e.split(/\r\n?|\n/)
```

Where `e` is `undefined`.

**Comment by sylvainjule** [comment] 2019-10-31 16:09
I cannot reproduce anymore in both Kirby 3.2.5 and 3.3.0-RC4, therefore I'm closing the ticket.
If it still happens for you please mention it and I'll reopen.

**Closed by sylvainjule** 2019-10-31 16:09 UTC
Labels: bug
