### ISSUE TITLE
[Bug] Unable to Override 'buttons' Option from Field Blueprint

### ISSUE THREAD

**Issue by luxlogica** [sylvainjule/kirby-markdown-field#51] opened 2019-01-12 05:04 UTC
Let's say I define a *'default_markdown.yml'* field blueprint, which sets out all the buttons I normally want in my standard markdown fields - it looks something like this:

``` yaml
buttons: 
  - headlines
    - h2
    - h3
    - h4
  - bold
  - italic
  - strikethrough
  - horizontal-rule
  - ul
  - ol
  - blockquote
  - code
  - image 
  - file 
  - pagelink
  - link
  - email
```

Now, somewhere else in my site, I'm going to extend this blueprint, wanting to override the 'buttons' option, because I want to use *less* buttons. So, I'd do something like this:

```yaml
byline:
  extends: fields/default_markdown
  buttons:
    - bold
    - italic
    - link
    - pagelink
    - email
```

Unfortunately, when I do this, I still get **all** the buttons from the original field blueprint - not the overridden, shorter list...

**Comment by sylvainjule** [comment] 2019-01-12 15:16
RC5? I cannot reproduce.

**Comment by sylvainjule** [comment] 2019-01-12 15:30
Oh ok, I found the issue. I tested it initially with more buttons in the extended field.

The problem is that when extending the option, the plugin isn't replacing it but merging the two. So the first 5 buttons are correctly overwritten but the additional buttons of the original field are still appended. Doesn't happen with the textarea field. I'm looking into it.

**Comment by sylvainjule** [comment] 2019-01-12 15:49
Nope, turns out the `textarea` field is behaving the same way.
I tested it with `italic` overriding `bold, italic`, so ended up with a single `italic` button only because the field is checking for duplicates (which is a nice features btw, I added it: https://github.com/sylvainjule/kirby-markdown-field/commit/956182ae938bd419b580c18ba454ac1fa6e1457a)

I've opened an issue here: https://github.com/k-next/kirby/issues/1349
So I'm closing this one.

**Closed by sylvainjule** 2019-01-12 15:49 UTC
Labels: bug
