### ISSUE TITLE
Undercore creating italics

### ISSUE THREAD

**Issue by LudwigBogner** [sylvainjule/kirby-markdown-field#68] opened 2019-03-03 17:36 UTC
Hello,

When using the option blank: true to enable the target _blank option for links, the text following a link will be italicised due to the underscore character.

With underscore:
![screen shot 2019-03-03 at 18 28 37](https://user-images.githubusercontent.com/2116283/53698863-7f59b700-3de2-11e9-8196-d9f497133091.png)

Without underscore:
![screen shot 2019-03-03 at 18 28 44](https://user-images.githubusercontent.com/2116283/53698864-7ff24d80-3de2-11e9-98cb-ab1b22ed5933.png)

**Comment by fabianmichael** [comment] 2019-03-04 09:57
Duplicate of #65

**Closed by fabianmichael** 2019-03-04 09:57 UTC
Labels: bug
