### ISSUE TITLE
fatal error if kirby is installed in a custom directory 

### ISSUE THREAD

**Issue by thomasfahrland** [sylvainjule/kirby-markdown-field#55] opened 2019-01-17 14:12 UTC
If you install Kirby in a custom directory (https://getkirby.com/docs/cookbook/installation/composer#installing-kirby-to-a-custom-directory), the plugin throws this error:
Warning: require(/var/www/htdocs/vendor/k-community/markdown-field/lib/fields/../../../../../kirby/config/fields/textarea.php): failed to open stream: No such file or directory in /var/www/htdocs/vendor/k-community/markdown-field/lib/fields/markdown.php on line 5

The path is falsely defined hard:
https://github.com/sylvainjule/kirby-markdown-field/blob/fe3d9df124668297422a9247d45fca8c308872c4/lib/fields/markdown.php#L5

**Comment by sylvainjule** [comment] 2019-01-17 14:16
Crap. The issue is that at this point, we can't use `$kirby->roots()` because Kirby isn't fully initialized yet. Thus the hardcoded path, which is not ideal of course, but for now I see no alternative?

See also:
https://github.com/getkirby/kirby/issues/1307

**Comment by distantnative** [comment] 2019-03-05 20:35
@sylvainjule Is that problem still persisting with Kirby 3.0.3? We tried to improve the initialisation, but it might still not work for all cases.

**Comment by sylvainjule** [comment] 2019-03-17 15:32
Seems fixed on my end, so I switched back to calling `kirby()->root()`.

**Closed** 2019-03-17 15:31 UTC
Labels: bug, help wanted
