### ISSUE TITLE
The field type "<field_name>" does not exist

### ISSUE THREAD

**Issue by iv-agatha** [sylvainjule/kirby-markdown-field#76] opened 2019-07-02 13:39 UTC
I'm using Kirby 3.2 and getting this error when using the markdown field. This is what my blueprint looks like:

```
title: Home

tabs:
  content:
    label: Content
    icon: document
    columns:
      - width: 2/3
        fields:
          page_content:
            label: Text
            type: markdown
            size: small
      - width: 1/3
        sections:
          files:
            type: files
```

![image](https://user-images.githubusercontent.com/22304204/60516614-1c9efc00-9cac-11e9-855f-c35b284be8f2.png)

**Comment by yeeno** [comment] 2019-07-14 14:03
Same error here. This happend since commit Jun 13, 2019, so if you check out an older version, it will work.

**Comment by Pechente** [comment] 2019-07-14 16:46
Can't confirm. Neither the commit on May 10th does work for me, nor release 1.1.0. Seems like this bug was introduced with Kirby 3.2.

**Comment by sylvainjule** [comment] 2019-07-14 16:58
I cannot reproduce this with 3.2.2. Just copy-pasted your snippet with no error 🤔
Is it the same version you're all using?

**Comment by yeeno** [comment] 2019-07-14 18:42
I just checked it again: commit May 10th is working, commit Jun 13 has the error. I use Kirby 3.2.2.

**Comment by iv-agatha** [comment] 2019-07-19 12:21
Found the culprit: [Kirby Builder](https://github.com/TimOetting/kirby-builder). Hopefully there's a way to make them work together.

**Comment by sylvainjule** [comment] 2019-07-19 13:03
Thank you for investigating, I have suggested a way to make it work in the builder's repo, I'm closing this since it seems to be related to interferences with other plugin(s) while following the Pluginkit guidelines. Feel free to re-open if not :)

**Closed by sylvainjule** 2019-07-19 13:03 UTC

**Comment by tkeil69575** [comment] 2020-06-24 21:36
I had the same problem: for me the culprit was the plugin **kirby-color** ...
