### ISSUE TITLE
400ms per keydown event.

### ISSUE THREAD

**Issue by itst** [sylvainjule/kirby-markdown-field#95] opened 2020-07-16 20:28 UTC
Hey people. I have an issue with my Kirby Panel. When typing content, the fronend slows down. Look at this. 400ms per keydown event.

![Bildschirmfoto 2020-06-24 um 09 31 31](https://user-images.githubusercontent.com/177044/87719420-9de00880-c7b3-11ea-94ed-3cc9fb8f2715.png)

Blueprint: https://pastebin.com/u15SuANU
Section: https://pastebin.com/pe3vGVVU

Any ideas?

That’s Kirby 3.3.5 and kirby-markdown-field 1.0.6

**Comment by seehat** [comment] 2020-08-05 04:57
I have the same issue with Kirby 3.4.1 and kirby makdown 1.0.6.

**Comment by sylvainjule** [comment] 2020-12-27 14:45
Apologies for the delay. The pastebin are no longer available. 

Could you setup a complete starterkit where you can reproduce the issue and share it so I have a ready-to-debug example? Because I can't reproduce these performances.

Maybe related to https://github.com/getkirby/kirby/issues/2736

**Comment by fabianmichael** [comment] 2021-04-30 09:08
@itst @seehat The upcoming version of the plugin has reached late alpha/early beta status and has a new engine (CodeMirror 6). Please give it a try and test, if the performance got better for you: https://github.com/sylvainjule/kirby-markdown-field/tree/next

**Comment by seehat** [comment] 2021-05-06 12:57
Yes, it looks and feels nice and the performance problems are gone for me. Kudos!

**Comment by fabianmichael** [comment] 2021-05-09 09:44
resolved in 2.0

**Closed by fabianmichael** 2021-05-09 09:44 UTC
Labels: bug, needs: information

**Comment by itst** [comment] 2021-05-20 08:45
Works for me, too! Thank you, great work!

**Comment by fabianmichael** [comment] 2021-05-31 17:29
@itst 

> Works for me, too! Thank you, great work!

Nice to hear that! :-)

> Any idea when you can release 2.0?

My plan was to wait for a stable CodeMirror 6 release … but that could take a while. I’ve been using the editor without any problems for several weeks now. If I don't encounter any more issues in the following weeks, I might release it earlier.

> And is there a funding possibility? Would like to toss a few coins in there.

Thanks for your offering. Currently, I don’t have anything set up for receiving donations … but maybe you want to support @marijnh instead. He is the creator of CodeMirror and (indirectly) did most of the work, to make this plugin possible. ;-) https://marijnhaverbeke.nl/fund/
